CREATE TABLE IF NOT EXISTS "photo_enrichment" (
	"contentdm_id" text PRIMARY KEY NOT NULL,
	"contentdm_url" text,
	"last_synced_at" timestamp with time zone,
	"source_record_hash" text,
	"enrichment_version" integer DEFAULT 1,
	"lat" numeric,
	"lng" numeric,
	"geo_confidence" text,
	"geo_source" text,
	"neighborhood_tag" text,
	"secondary_neighborhood_tag" text,
	"branch_service_area" text,
	"date_start" date,
	"date_end" date,
	"date_precision" text,
	"date_display" text,
	"patron_caption" text,
	"librarian_note" text,
	"librarian_note_author" text,
	"librarian_note_updated_at" timestamp with time zone,
	"story_hook" text,
	"public_status" text DEFAULT 'draft',
	"featured_weight" integer,
	"themes" text[],
	"rephoto_eligible" boolean,
	"rephoto_bearing" numeric,
	"rephoto_modern_lat" numeric,
	"rephoto_modern_lng" numeric,
	"rephoto_notes" text,
	"caption_quality" text,
	"metadata_gap_flags" text[],
	"accessibility_alt_text" text,
	"rights_display" text,
	"rights_notes" text,
	"reuse_cleared" boolean,
	"physical_location" text,
	"request_scan_eligible" boolean,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scan_review" (
	"chc_id" text PRIMARY KEY NOT NULL,
	"master_path" text,
	"jpeg_url" text,
	"jpeg_path" text,
	"derive" jsonb,
	"vlm" jsonb,
	"status" text DEFAULT 'discovered' NOT NULL,
	"error" text,
	"review" jsonb,
	"enrichment" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
